sudo: required
services:
    - docker

# Build images to be tested
before_install:
    - docker build -t soundestmammal/oasis -f ./client/Dockerfile.dev ./client

# Run tests here
script:
    - docker run -e CI=true soundestmammal/oasis npm test

# If tests pass && branch=containerize -> push images to DH
after_success:
    - docker build -t soundestmammal/oasis-client ./client
    - docker build -t soundestmammal/oasis-nginx ./nginx
    - docker build -t soundestmammal/oasis-server ./server
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push soundestmammal/oasis-client
    - docker push soundestmammal/oasis-nginx
    - docker push soundestmammal/oasis-server
# if branch=containerize -> deploy to EB
deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: oasis
    env: Oasis-env
    bucket_name: elasticbeanstalk-us-east-2-670541471230
    bucket_path: oasis
    on:
        branch: containerize
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
