sudo: required
services:
    - docker

# Build images to be tested
before_install:
    - docker build -t soundestmammal/oasis -f ./client/Dockerfile.dev ./client

# Run tests here
script:
    - docker run -e CI=true soundestmammal/oasis npm test

# If tests pass && branch=master : deploy to dockerhub
deploy:
    provider: script
    script: bash ./deploy.sh
    on:
        branch: containerize
