version: 2
jobs:
  test_client:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          command: |
            docker build -t soundestmammal/oasis-client-test -f ./client/Dockerfile.dev ./client
            docker run -e CI=true soundestmammal/oasis-client-test npm test
  upload_images:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          command: |
            docker build -t soundestmammal/oasis-client ./client
            docker build -t soundestmammal/oasis-nginx ./nginx
            docker build -t soundestmammal/oasis-server ./server
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
            docker push soundestmammal/oasis-client
            docker push soundestmammal/oasis-nginx
            docker push soundestmammal/oasis-server
  deploy:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          command: apt-get install less

      - run:
          command: bash ./.circleci/ci_script.sh

workflows:
  version: 2
  Oasis_Workflow:
    jobs:
      - test_client
      - upload_images:
          requires:
            - test_client
      - deploy:
          requires:
            - test_client
            - upload_images
          filters:
            branches:
              only: containerize
